{% set version = "0.5.0" %}

package:
  name: nipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nipy/nipy-{{ version }}.tar.gz
  sha256: a8a2c97ce854fece4aced5a6394b9fdca5846150ad6d2a36b86590924af3c848

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.12.1
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=1.0.0
    - sympy >=1.0
    - nibabel >=2.0

test:
  imports:
    - nipy
    - nipy.algorithms
    - nipy.core
    - nipy.interfaces
    - nipy.io
    - nipy.labs
    - nipy.modalities
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://nipy.org/nipy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Neuroimaging in Python FMRI analysis package

extra:
  recipe-maintainers:
    - ocefpaf
