{% set name = "nipy" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nipy-{{ version }}.tar.gz
  sha256: 0539f69d5e1531e4fc6f14ce2531e3454f08d9bc45642cc86426559ff41c52b9
  patches:
    - no-int-conversion.patch

build:
  entry_points:
    - nipy_3dto4d = nipy.cli.img3dto4d:main
    - nipy_4dto3d = nipy.cli.img4dto3d:main
    - nipy_4d_realign = nipy.cli.realign4d:main
    - nipy_tsdiffana = nipy.cli.tsdiffana:main
    - nipy_diagnose = nipy.cli.diagnose:main
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - meson-python >=0.13
    - ninja
    - setuptools
    - cython >=3
    - pip
    - numpy >=1.22,<2.0dev0
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numpy >=1.22,<2.0dev0
    - scipy >=1.8
    - nibabel >=3.2
    - sympy >=1.9
    - transforms3d

test:
  imports:
    - nipy
  commands:
    - pip check
    - nipy_3dto4d --help
    - nipy_4dto3d --help
    - nipy_4d_realign --help
    - nipy_tsdiffana --help
    - nipy_diagnose --help
  requires:
    - pip
    - matplotlib

about:
  home: http://nipy.org/nipy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Neuroimaging in Python FMRI analysis package'

extra:
  recipe-maintainers:
    - ocefpaf
