{% set version = "0.6.0" %}

package:
  name: nipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nipy/nipy-{{ version }}.tar.gz
  sha256: 0539f69d5e1531e4fc6f14ce2531e3454f08d9bc45642cc86426559ff41c52b9

build:
  number: 0
  # due to the scipy pin, remove once a new release is out
  skip: true  # [py>=38]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - cython >=0.12.1
    - numpy
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - numpy <1.18
    - scipy >=0.9.0,<1.3.0
    - sympy >=0.7.0
    - nibabel >=1.2.0

test:
  imports:
    - nipy
    - nipy.algorithms
    - nipy.core
    - nipy.interfaces
    - nipy.io
    - nipy.labs
    - nipy.modalities

about:
  home: http://nipy.org/nipy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Neuroimaging in Python FMRI analysis package'

extra:
  recipe-maintainers:
    - ocefpaf
