{% set version = "0.4.2" %}

package:
  name: nipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nipy/nipy-{{ version }}.tar.gz
  sha256: d30bed60e1662f0b79ef665396e98b1b2e57b1734d3d11510a3d7fa66d18c7de

build:
  number: 1003
  # due to the scipy pin, remove once a new release is out
  skip: True  # [py>=38]
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - cython >=0.12.1
    - numpy
  run:
    - python
    - numpy <1.18
    - scipy >=0.9.0,<1.3.0
    - sympy >=0.7.0
    - nibabel >=1.2.0

test:
  imports:
    - nipy
    - nipy.algorithms
    - nipy.core
    - nipy.interfaces
    - nipy.io
    - nipy.labs
    - nipy.modalities

about:
  home: http://nipy.org/nipy
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'Neuroimaging in Python FMRI analysis package'

extra:
  recipe-maintainers:
    - ocefpaf
