{% set name = "nipy" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nipy-{{ version }}.tar.gz
  sha256: a8a2c97ce854fece4aced5a6394b9fdca5846150ad6d2a36b86590924af3c848

build:
  number: 0
  skip: True  # [py<36]
  entry_points:
    - nipy_3dto4d = nipy.cli.img3dto4d:main
    - nipy_4dto3d = nipy.cli.img4dto3d:main
    - nipy_4d_realign = nipy.cli.realign4d:main
    - nipy_tsdiffana = nipy.cli.tsdiffana:main
    - nipy_diagnose = nipy.cli.diagnose:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython >=0.12.1
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - nibabel >=2.0
    - scipy >=1.0.0
    - sympy >=1.0

test:
  imports:
    - nipy
  commands:
    - pip check
    - nipy_3dto4d --help
    - nipy_4dto3d --help
    - nipy_4d_realign --help
    - nipy_tsdiffana --help
    - nipy_diagnose --help
  requires:
    - pip
    - matplotlib-base

about:
  home: http://nipy.org/nipy
  summary: A python package for analysis of neuroimaging data
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
