travis:
  secure:
    BINSTAR_TOKEN: S/j0m5mPF4KX4exq5FtH8VQImgvMMKfbrfbXL0gV6k+CVh3q7yVecGzL14uMUReiKSQASI8JOVmR16MGfT/r/GZcqv89/dw2rpNtCxSJyzqSP2uu3V/gWsZjMIOM1IUYyugHN/+eIKn+6MTIsj21hsLHm3XS4Rj0ambuSpaMCAHB41cXYQ5yD50w/JsY0Rqf9x3tvf9iGJgwEwFAxpsBszLLGBSaDzchu/9y+DB9VhiYVZBHvFRN3Pe7c64DY/3KOrklmZnwvPDOX5iyglKmAUOafjpm/DfDAMmP4MIK6+Bfp/upqyzkLcFd5C8d1muu5BLj7hTIwz1a0kyYpB/9VyM/xkGUj+uRWi9Dl09YlU/1jxP9csd/4yyMIm6cK1f1njHlWsMypEGN8cyOjmaxI8Xv9m3pqbmO9HpI8sfxhHBIdbDraSxf8JH1e5uORgFd99nzpaxBYXqlk483wibIRPGBrizLVDZMdH4Gh1y/9lYPOmj62ZTfgmreeyh6tpayiAOI/jM4pTr2g/RBolTyoySPF+cMbXZBM+bZYnDkyR9KsY7kYoWpQj4h8XnLgKkWIA18DVgisMSVZ0byLv5DqukTUUGlPv/RIGx7ORJbDfZ+8fPMy5q1J0XuFwCRudQ0TsYOjaQ6+Fh/W41YUbJ8mUYeATbQGE3kgFeOfJD4fAg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
