travis:
  secure:
    BINSTAR_TOKEN: RHV2vo/SrsKQ43uHlqT4b2qdWiDcaR3EskHLWBiuxK/izp0eMdcY3Ly3XOO6M7XTE1k6OgbNices+jYb6yvYzX6Zkr0oirfIPUkv8IfhjzTP6y2scMaSmJ5Y77+P7Bk2sM5FPZ6WXoQr8Ie8xPQFurQ2g9MjDvBWaLgbbwfyzDQ7qyHYZpO1Ae+8fS5ilPnGsRuPXK1u8zuix9Pg5I9ZQhE535AdRB5h7Ezf4V7p1KUTWY/P32u/8lA7QQTbrh5Eh0ByC6SuWhpsz+KYhkmzXPOpcsJKJA4f0o07u+6E6F/9aq2FfSMroxj96nBaUTCeJ7U9FrbA35L2ux66XxbANAH3le4ymdj3Ux0EWmOnvrouy9OuF0ZRwyfPiHQ84AeKHaa82/kffbReriMMPh4KxB00N2RhJ+U3+dHZ1LzJLE/bDdymnJFqQcrCjeWbDjsNFToZzUxABwJ1cZIsgHhveVT1dIdzLNDkUXk394Ogp1+2hRyjoE+9wMRmzdO28K7wEE+CKyEz3QFZ6/mV+SAsM4z9lU1+r5MkP0GFik7ZsgS477zT0KnX5nLkk+4FdFzok4bIj7wveni2Lpdl2ZKy7kp8H8dpfUx0MLShgJjC4Y4yGdgtosmsvwOCUNH4/TbMVsUuqGGg7S5BiEDmX8RIgdEL4DcC7HEx5X+3m0c5KlQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
