travis:
  secure:
    BINSTAR_TOKEN: mvYDsGOw7ZLTltDy0WVH3RPcQFTsIVm5lNmUTZFKcwJ6h3XCznKM8Ji/psujbLq6qjQB9mPv8wtLIy5pvNsKw4Ox1Lj9csEVlspd+n3lY17mFKXM3w8XIm+jG00+7xTL6C85hro+/CyC0yzJ2fhUSQOj/YheLqIREzOLLcoPGwEx6L5r7/URZBmfyH/BOLA3dsFfjRA5O7qSTZAHjUrvX3Kzcb/0Wt+siFHtNujgTcgBok9FnmjnwuqCFWrsTx8Wqp/2ngDjQNMFAuvUeRd9i0qjGI3JLrUkws3J9gSav+lmYrkP79bwlzFKQ0YjMoM6Un+c9winSVyjII78PwtFjzcVjIyiaOadOJ2fNq0uNLVtqPrYQqh1r4Xngg8lJByTtju58NakxR4Qd/iQuVdKR5YtvaRqquwe49bnnYCukSHTMDEhJ+sYmy5qVdAJTmc7dFul0+PEy6pdE0n8YXAkwUbM1nyo9oj3GWwDLtFmYOrFz3WGrTC47iWq9NOtzqzYblnTt+kFYaDr3qk0RjROZx/uEkq93hy6MLyoYORFCm1OwYohAUgn+yk4BHn8tKr5oK+W2Qb8QZtH+mxFWFevSf+YP59lrvydIzmScnL+HN6KsPQyMOUL3aCWvAUYZJuGZRmy9toZ+Uha37wsVdL6TBjQ8a8udi1LPkdQWWMrZKc=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
